
import { Asset, AssetCategory, DataSource } from './types';

export const INITIAL_WATCHLIST_ASSETS: string[] = ['Gold (XAU/USD)', 'Bitcoin (BTCUSD)', 'EUR/USD', 'Dow Jones (DJI / US30)'];

export const ASSETS: Asset[] = [
  // Crypto
  { name: 'Bitcoin (BTCUSD)', category: AssetCategory.CRYPTO },
  { name: 'Ethereum (ETHUSD)', category: AssetCategory.CRYPTO },
  { name: 'Solana (SOLUSD)', category: AssetCategory.CRYPTO },
  { name: 'XRP (XRPUSD)', category: AssetCategory.CRYPTO },
  { name: 'Litecoin (LTCUSD)', category: AssetCategory.CRYPTO },
  { name: 'Bitcoin Cash (BCHUSD)', category: AssetCategory.CRYPTO },
  { name: 'Dogecoin (DOGEUSD)', category: AssetCategory.CRYPTO },
  { name: 'BNB (BNBUSD)', category: AssetCategory.CRYPTO },
  { name: 'Tether (USDTUSD)', category: AssetCategory.CRYPTO },
  // Indices
  { name: 'AUS200', category: AssetCategory.INDICES },
  { name: 'DAX (GER40)', category: AssetCategory.INDICES },
  { name: 'Dow Jones (DJI / US30)', category: AssetCategory.INDICES },
  { name: 'EUSTX50', category: AssetCategory.INDICES },
  { name: 'FRA40', category: AssetCategory.INDICES },
  { name: 'Hang Seng (HK50)', category: AssetCategory.INDICES },
  { name: 'NASDAQ 100 (NDX / US100)', category: AssetCategory.INDICES },
  { name: 'Nikkei 225 (JPN225)', category: AssetCategory.INDICES },
  { name: 'S&P 500 (INX)', category: AssetCategory.INDICES },
  { name: 'SPA35', category: AssetCategory.INDICES },
  { name: 'SWI20', category: AssetCategory.INDICES },
  { name: 'UK100', category: AssetCategory.INDICES },
  { name: 'U.S. Dollar Index (DXY)', category: AssetCategory.INDICES },
  { name: 'US2000', category: AssetCategory.INDICES },
  // Forex
  { name: 'AUD/CAD', category: AssetCategory.FOREX },
  { name: 'AUD/CHF', category: AssetCategory.FOREX },
  { name: 'AUD/JPY', category: AssetCategory.FOREX },
  { name: 'AUD/NZD', category: AssetCategory.FOREX },
  { name: 'AUD/SGD', category: AssetCategory.FOREX },
  { name: 'AUD/USD', category: AssetCategory.FOREX },
  { name: 'CAD/CHF', category: AssetCategory.FOREX },
  { name: 'CAD/JPY', category: AssetCategory.FOREX },
  { name: 'CHF/JPY', category: AssetCategory.FOREX },
  { name: 'CHF/SGD', category: AssetCategory.FOREX },
  { name: 'EUR/AUD', category: AssetCategory.FOREX },
  { name: 'EUR/CAD', category: AssetCategory.FOREX },
  { name: 'EUR/CHF', category: AssetCategory.FOREX },
  { name: 'EUR/CZK', category: AssetCategory.FOREX },
  { name: 'EUR/GBP', category: AssetCategory.FOREX },
  { name: 'EUR/HKD', category: AssetCategory.FOREX },
  { name: 'EUR/ILS', category: AssetCategory.FOREX },
  { name: 'EUR/JPY', category: AssetCategory.FOREX },
  { name: 'EUR/NZD', category: AssetCategory.FOREX },
  { name: 'EUR/RON', category: AssetCategory.FOREX },
  { name: 'EUR/RUB', category: AssetCategory.FOREX },
  { name: 'EUR/SGD', category: AssetCategory.FOREX },
  { name: 'EUR/TRY', category: AssetCategory.FOREX },
  { name: 'EUR/USD', category: AssetCategory.FOREX },
  { name: 'EUR/ZAR', category: AssetCategory.FOREX },
  { name: 'GBP/AUD', category: AssetCategory.FOREX },
  { name: 'GBP/CAD', category: AssetCategory.FOREX },
  { name: 'GBP/CHF', category: AssetCategory.FOREX },
  { name: 'GBP/CZK', category: AssetCategory.FOREX },
  { name: 'GBP/HKD', category: AssetCategory.FOREX },
  { name: 'GBP/JPY', category: AssetCategory.FOREX },
  { name: 'GBP/NZD', category: AssetCategory.FOREX },
  { name: 'GBP/SGD', category: AssetCategory.FOREX },
  { name: 'GBP/TRY', category: AssetCategory.FOREX },
  { name: 'GBP/USD', category: AssetCategory.FOREX },
  { name: 'GBP/ZAR', category: AssetCategory.FOREX },
  { name: 'NZD/CAD', category: AssetCategory.FOREX },
  { name: 'NZD/CHF', category: AssetCategory.FOREX },
  { name: 'NZD/JPY', category: AssetCategory.FOREX },
  { name: 'NZD/SGD', category: AssetCategory.FOREX },
  { name: 'NZD/USD', category: AssetCategory.FOREX },
  { name: 'SGD/JPY', category: AssetCategory.FOREX },
  { name: 'USD/CAD', category: AssetCategory.FOREX },
  { name: 'USD/CHF', category: AssetCategory.FOREX },
  { name: 'USD/CNH', category: AssetCategory.FOREX },
  { name: 'USD/CZK', category: AssetCategory.FOREX },
  { name: 'USD/DKK', category: AssetCategory.FOREX },
  { name: 'USD/HKD', category: AssetCategory.FOREX },
  { name: 'USD/HUF', category: AssetCategory.FOREX },
  { name: 'USD/ILS', category: AssetCategory.FOREX },
  { name: 'USD/JPY', category: AssetCategory.FOREX },
  { name: 'USD/MXN', category: AssetCategory.FOREX },
  { name: 'USD/NOK', category: AssetCategory.FOREX },
  { name: 'USD/PLN', category: AssetCategory.FOREX },
  { name: 'USD/RON', category: AssetCategory.FOREX },
  { name: 'USD/RUB', category: AssetCategory.FOREX },
  { name: 'USD/SEK', category: AssetCategory.FOREX },
  { name: 'USD/SGD', category: AssetCategory.FOREX },
  { name: 'USD/THB', category: AssetCategory.FOREX },
  { name: 'USD/ZAR', category: AssetCategory.FOREX },
  { name: 'ZAR/JPY', category: AssetCategory.FOREX },
  // Commodities
  { name: 'Gold (XAU/EUR)', category: AssetCategory.COMMODITIES },
  { name: 'Gold (XAU/JPY)', category: AssetCategory.COMMODITIES },
  { name: 'Gold (XAU/USD)', category: AssetCategory.COMMODITIES },
  { name: 'Natural Gas (XNG/USD)', category: AssetCategory.COMMODITIES },
  { name: 'Silver (XAG/EUR)', category: AssetCategory.COMMODITIES },
  { name: 'Silver (XAG/USD)', category: AssetCategory.COMMODITIES },
  { name: 'UKOIL', category: AssetCategory.COMMODITIES },
  { name: 'US Oil Basket (USBKT)', category: AssetCategory.COMMODITIES },
  { name: 'WTI Crude Oil (USOIL)', category: AssetCategory.COMMODITIES },
];

export const INITIAL_DATA_SOURCES: DataSource[] = [
    { name: 'Actionforex.com', url: 'https://www.actionforex.com' },
    { name: 'Ainvest.com', url: 'https://www.ainvest.com' },
    { name: 'Altindex.com', url: 'https://altindex.com' },
    { name: 'Arabictrader.com', url: 'https://www.arabictrader.com' },
    { name: 'AXA-IM.co.uk', url: 'https://www.axa-im.co.uk' },
    { name: 'BankOfEngland.co.uk', url: 'https://www.bankofengland.co.uk' },
    { name: 'Barchart.com', url: 'https://www.barchart.com' },
    { name: 'BEA.gov', url: 'https://www.bea.gov' },
    { name: 'Binance.com', url: 'https://www.binance.com' },
    { name: 'Bitbo.io', url: 'https://bitbo.io' },
    { name: 'Blockonomi', url: 'https://blockonomi.com' },
    { name: 'Blockworks.co', url: 'https://blockworks.co' },
    { name: 'BNA.bh', url: 'https://www.bna.bh' },
    { name: 'Businesstoday.com.my', url: 'https://www.businesstoday.com.my' },
    { name: 'Chinadailyasia.com', url: 'https://www.chinadailyasia.com' },
    { name: 'Coinbase.com', url: 'https://www.coinbase.com' },
    { name: 'Coincodex.com', url: 'https://coincodex.com' },
    { name: 'Coingecko.com', url: 'https://www.coingecko.com' },
    { name: 'Coinmarketcap.com', url: 'https://coinmarketcap.com' },
    { name: 'Commbank.com.au', url: 'https://www.commbank.com.au' },
    { name: 'Crypto.news', url: 'https://crypto.news' },
    { name: 'Cryptodnes.bg', url: 'https://cryptodnes.bg' },
    { name: 'Dailyforex.com', url: 'https://www.dailyforex.com' },
    { name: 'Dbs.com.hk', url: 'https://www.dbs.com.hk' },
    { name: 'Deutschewealth.com', url: 'https://www.deutschewealth.com' },
    { name: 'Discoveryalert.com.au', url: 'https://www.discoveryalert.com.au' },
    { name: 'Economic Times', url: 'https://economictimes.indiatimes.com' },
    { name: 'Efginternational.com', url: 'https://www.efginternational.com' },
    { name: 'Europa.eu', url: 'https://europa.eu' },
    { name: 'Financefeeds.com', url: 'https://financefeeds.com' },
    { name: 'FlyEptPortugal.com', url: 'https://www.flyeptportugal.com' },
    { name: 'Forex.com', url: 'https://www.forex.com' },
    { name: 'Fortrade.com', url: 'https://www.fortrade.com' },
    { name: 'Fxempire.com', url: 'https://www.fxempire.com' },
    { name: 'FXLeaders.com', url: 'https://www.fxleaders.com' },
    { name: 'FXStreet.com', url: 'https://www.fxstreet.com' },
    { name: 'Fxview.com', url: 'https://www.fxview.com' },
    { name: 'Gainesvillecoins.com', url: 'https://www.gainesvillecoins.com' },
    { name: 'GlobalBankingAndFinance.com', url: 'https://www.globalbankingandfinance.com' },
    { name: 'Gold.org', url: 'https://www.gold.org' },
    { name: 'Growbeansprout.com', url: 'https://growbeansprout.com' },
    { name: 'Hkeconomy.gov.hk', url: 'https://www.hkeconomy.gov.hk' },
    { name: 'Holder.io', url: 'https://holder.io' },
    { name: 'Investing.com', url: 'https://www.investing.com' },
    { name: 'Investtech.com', url: 'https://www.investtech.com' },
    { name: 'Investx.com', url: 'https://investx.com' },
    { name: 'Jpmorgan.com', url: 'https://www.jpmorgan.com' },
    { name: 'Kagels-trading.com', url: 'https://kagels-trading.com' },
    { name: 'Kraken.com', url: 'https://www.kraken.com' },
    { name: 'Kucoin.com', url: 'https://www.kucoin.com' },
    { name: 'Litefinance.org', url: 'https://www.litefinance.org' },
    { name: 'Livemint.com', url: 'https://www.livemint.com' },
    { name: 'Marketpulse.com', url: 'https://www.marketpulse.com' },
    { name: 'Marketscreener.com', url: 'https://www.marketscreener.com' },
    { name: 'Mitrade.com', url: 'https://www.mitrade.com' },
    { name: 'Nasdaq.com', url: 'https://www.nasdaq.com' },
    { name: 'Noortrends.ae', url: 'https://noortrends.ae' },
    { name: 'Nordea.com', url: 'https://www.nordea.com' },
    { name: 'Oanda.com', url: 'https://www.oanda.com' },
    { name: 'ONS.gov.uk', url: 'https://www.ons.gov.uk' },
    { name: 'Oppenheimer', url: 'https://www.oppenheimer.com' },
    { name: 'Parliament.uk', url: 'https://www.parliament.uk' },
    { name: 'RBA.gov.au', url: 'https://www.rba.gov.au' },
    { name: 'Saxo Bank', url: 'https://www.home.saxo' },
    { name: 'Scmp.com', url: 'https://www.scmp.com' },
    { name: 'Seeking Alpha', url: 'https://seekingalpha.com' },
    { name: 'SEIC.com', url: 'https://www.seic.com' },
    { name: 'Serrarigroup.com', url: 'https://www.serrarigroup.com' },
    { name: 'Sky.com', url: 'https://www.sky.com' },
    { name: 'Spglobal.com', url: 'https://www.spglobal.com' },
    { name: 'Ssga.com', url: 'https://www.ssga.com' },
    { name: 'Thearmchairtrader.com', url: 'https://www.thearmchairtrader.com' },
    { name: 'Theblock.co', url: 'https://www.theblock.co' },
    { name: 'Thecurrencyanalytics.com', url: 'https://thecurrencyanalytics.com' },
    { name: 'TipRanks.com', url: 'https://www.tipranks.com' },
    { name: 'Tradestation.com', url: 'https://www.tradestation.com' },
    { name: 'TradingEconomics.com', url: 'https://www.tradingeconomics.com' },
    { name: 'Tradingview.com', url: 'https://www.tradingview.com' },
    { name: 'Usgoldbureau.com', url: 'https://www.usgoldbureau.com' },
    { name: 'Vanguard.com', url: 'https://www.vanguard.com' }
];